version: 0.2

phases:
  pre_build:
    run-as: root
    commands:
      - yum -y install git
      - git clone --depth 1 https://github.com/LoansBot/logging.git
      - git clone --depth 1 https://github.com/LoansBot/shared.git
      - mv logging/requirements.txt logging/logging-requirements.txt
      - mv shared/requirements.txt shared/shared-requirements.txt
artifacts:
  files:
     - src/**/*
     - logging/src/**/*
     - logging/logging-requirements.txt
     - shared/src/**/*
     - shared/shared-requirements.txt
     - requirements.txt
     - scripts/**/*
     - appspec.yml
     - cfg/**/*
