name: CI

on: [push]

jobs:
  test_loansbot:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.7, 3.8]
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq
        ports:
          - 5672/tcp
      memcached:
        image: memcached
        ports:
          - 11211/tcp
      arangodb:
        image: arangodb/arangodb
        ports:
          - 8529/tcp
        env:
          ARANGO_ROOT_PASSWORD: mango
    steps:
    - name: Setup Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    - name: Fetch LoansBot/loansbot
      uses: actions/checkout@v2
      with:
        path: ./loansbot
    - name: Fetch LoansBot/logging
      uses: actions/checkout@v2
      with:
        repository: LoansBot/logging
        path: ./logging
    - name: Fetch LoansBot/shared
      uses: actions/checkout@v2
      with:
        repository: LoansBot/shared
        path: ./shared
    - name: Building working directory
      run: |
        mkdir ./working
        mv ./loansbot/src ./working/src
        mv ./loansbot/tests ./working/tests
        mv ./logging/src/lblogging ./working/src/lblogging
        mv ./shared/src/lbshared ./working/src/lbshared
    - name: Generic python setup
      run: |
        python -m pip install --upgrade pip
        sudo apt update
        sudo apt install -yqq build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev postgresql-common libpq-dev postgresql-client
    - name: Installing logging dependencies
      run: |
        python -m pip install -r ./logging/requirements.txt
    - name: Installing shared dependencies
      run: |
        python -m pip install -r ./shared/requirements.txt
    - name: Installing our dependencies
      run: |
        python -m pip install -r ./loansbot/requirements.txt
    - name: Lint with flake8
      working-directory: ./working
      run: |
        flake8 . --count --select=E9,F63,F7,F82,F841,E302,E303,F401,E261,E306,E131,W292 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Fetch LoansBot/database
      uses: actions/checkout@v2
      with:
        repository: LoansBot/database
        path: ./database
    - name: Setup database dependencies
      run: |
        python -m pip install -r ./database/requirements.txt
    - name: Initialize database
      working-directory: ./database/src
      run: |
        python run_migrations.py
      env:
        DATABASE_HOST: localhost
        DATABASE_PORT: ${{ job.services.postgres.ports['5432'] }}
        DATABASE_USER: postgres
        DATABASE_PASSWORD: dev
        DATABASE_DBNAME: postgres
    - name: Run tests
      working-directory: ./working/tests
      run: |
        python -m unittest discover -s .
      env:
        KARMA_MIN: 1000
        ACCOUNT_AGE_SECONDS_MIN: 7776000
    - name: Get database logs
      if: always()
      working-directory: working/src
      run: |
        python -m lblogging.query
      env:
        PGHOST: localhost
        PGPORT: ${{ job.services.postgres.ports['5432'] }}
        PGDATABASE: postgres
        PGUSER: postgres
        PGPASSWORD: dev
